/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Handle Completions */
        post: operations["handle_completions_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/translations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Translate File */
        post: operations["translate_file_v1_audio_translations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/transcriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transcribe File */
        post: operations["transcribe_file_v1_audio_transcriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Local Models */
        get: operations["list_local_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Local Audio Models */
        get: operations["list_local_audio_models_v1_audio_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Local Audio Voices */
        get: operations["list_local_audio_voices_v1_audio_voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Local Model */
        get: operations["get_local_model_v1_models__model_id__get"];
        put?: never;
        /** Download Remote Model */
        post: operations["download_remote_model_v1_models__model_id__post"];
        /** Delete Model */
        delete: operations["delete_model_v1_models__model_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Remote Models */
        get: operations["get_remote_models_v1_registry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a list of loaded models. */
        get: operations["get_running_models_api_ps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ps/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load a model into memory. */
        post: operations["load_model_route_api_ps__model_id__post"];
        /** Unload a model from memory. */
        delete: operations["stop_running_model_api_ps__model_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/realtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Realtime Webrtc */
        post: operations["realtime_webrtc_v1_realtime_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/speech": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synthesize */
        post: operations["synthesize_v1_audio_speech_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/speech/embedding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Speech Embedding */
        post: operations["create_speech_embedding_v1_audio_speech_embedding_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/speech/timestamps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detect Speech Timestamps */
        post: operations["detect_speech_timestamps_v1_audio_speech_timestamps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/diarization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Diarize Audio */
        post: operations["diarize_audio_v1_audio_diarization_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Annotation */
        Annotation: {
            /**
             * Type
             * @constant
             */
            type: "url_citation";
            url_citation: components["schemas"]["AnnotationURLCitation"];
        } & {
            [key: string]: unknown;
        };
        /** AnnotationURLCitation */
        AnnotationURLCitation: {
            /** End Index */
            end_index: number;
            /** Start Index */
            start_index: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
        } & {
            [key: string]: unknown;
        };
        /** Audio */
        Audio: {
            /** Id */
            id: string;
        };
        /** Body_create_speech_embedding_v1_audio_speech_embedding_post */
        Body_create_speech_embedding_v1_audio_speech_embedding_post: {
            /** Model */
            model: string;
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_detect_speech_timestamps_v1_audio_speech_timestamps_post */
        Body_detect_speech_timestamps_v1_audio_speech_timestamps_post: {
            /**
             * Model
             * @default silero_vad_v5
             */
            model: string;
            /**
             * Threshold
             * @description Speech threshold. Silero VAD outputs speech probabilities for each audio chunk, probabilities ABOVE this value are considered as SPEECH. It is better to tune this parameter for each dataset separately, but "lazy" 0.5 is pretty good for most datasets.
             * @default 0.75
             */
            threshold: number;
            /**
             * Neg Threshold
             * @description Silence threshold for determining the end of speech. If a probability is lower
             *             than neg_threshold, it is always considered silence. Values higher than neg_threshold
             *             are only considered speech if the previous sample was classified as speech; otherwise,
             *             they are treated as silence. This parameter helps refine the detection of speech
             *              transitions, ensuring smoother segment boundaries.
             */
            neg_threshold?: number | null;
            /**
             * Min Speech Duration Ms
             * @description Final speech chunks shorter min_speech_duration_ms are thrown out.
             * @default 0
             */
            min_speech_duration_ms: number;
            /**
             * Max Speech Duration S
             * @description Maximum duration of speech chunks in seconds. Chunks longer
             *             than max_speech_duration_s will be split at the timestamp of the last silence that
             *             lasts more than 100ms (if any), to prevent aggressive cutting. Otherwise, they will be
             *             split aggressively just before max_speech_duration_s.
             */
            max_speech_duration_s?: number;
            /**
             * Min Silence Duration Ms
             * @description In the end of each speech chunk wait for min_silence_duration_ms
             *             before separating it
             * @default 1000
             */
            min_silence_duration_ms: number;
            /**
             * Speech Pad Ms
             * @description Final speech chunks are padded by speech_pad_ms each side
             * @default 0
             */
            speech_pad_ms: number;
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_diarize_audio_v1_audio_diarization_post */
        Body_diarize_audio_v1_audio_diarization_post: {
            /** Known Speaker Names */
            known_speaker_names?: string[] | null;
            /** Known Speaker References */
            known_speaker_references?: string[] | null;
            /**
             * Response Format
             * @default json
             */
            response_format: ("json" | "rttm") | null;
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_transcribe_file_v1_audio_transcriptions_post */
        Body_transcribe_file_v1_audio_transcriptions_post: {
            /** Model */
            model: string;
            /** Language */
            language?: string | null;
            /** Prompt */
            prompt?: string | null;
            /** @default json */
            response_format: components["schemas"]["ResponseFormat"];
            /**
             * Temperature
             * @default 0
             */
            temperature: number;
            /**
             * Timestamp Granularities
             * @default [
             *       "segment"
             *     ]
             */
            timestamp_granularities: ("segment" | "word")[];
            /**
             * Stream
             * @default false
             */
            stream: boolean;
            /** Hotwords */
            hotwords?: string | null;
            /**
             * Without Timestamps
             * @default true
             */
            without_timestamps: boolean;
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_translate_file_v1_audio_translations_post */
        Body_translate_file_v1_audio_translations_post: {
            /** Model */
            model: string;
            /** Prompt */
            prompt?: string | null;
            /** @default json */
            response_format: components["schemas"]["ResponseFormat"];
            /**
             * Temperature
             * @default 0
             */
            temperature: number;
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** ChatCompletion */
        ChatCompletion: {
            /** Id */
            id: string;
            /** Choices */
            choices: components["schemas"]["openai__types__chat__chat_completion__Choice"][];
            /** Created */
            created: number;
            /** Model */
            model: string;
            /**
             * Object
             * @constant
             */
            object: "chat.completion";
            /** Service Tier */
            service_tier?: ("auto" | "default" | "flex" | "scale" | "priority") | null;
            /** System Fingerprint */
            system_fingerprint?: string | null;
            usage?: components["schemas"]["CompletionUsage"] | null;
        } & {
            [key: string]: unknown;
        };
        /** ChatCompletionAssistantMessageParam */
        ChatCompletionAssistantMessageParam: {
            /**
             * Role
             * @constant
             */
            role: "assistant";
            audio?: components["schemas"]["Audio"] | null;
            /** Content */
            content?: string | (components["schemas"]["ChatCompletionContentPartTextParam"] | components["schemas"]["ChatCompletionContentPartRefusalParam"])[] | null;
            function_call?: components["schemas"]["speaches__types__chat__FunctionCall"] | null;
            /** Name */
            name?: string | null;
            /** Refusal */
            refusal?: string | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ChatCompletionMessageToolCallParam"][] | null;
        };
        /** ChatCompletionAudio */
        ChatCompletionAudio: {
            /** Id */
            id: string;
            /** Data */
            data: string;
            /** Expires At */
            expires_at: number;
            /** Transcript */
            transcript: string;
        } & {
            [key: string]: unknown;
        };
        /** ChatCompletionAudioParam */
        ChatCompletionAudioParam: {
            /**
             * Format
             * @enum {string}
             */
            format: "wav" | "mp3" | "flac" | "opus" | "pcm16";
            /** Voice */
            voice: string;
        };
        /** ChatCompletionChunk */
        ChatCompletionChunk: {
            /** Id */
            id: string;
            /** Choices */
            choices: components["schemas"]["openai__types__chat__chat_completion_chunk__Choice"][];
            /** Created */
            created: number;
            /** Model */
            model: string;
            /**
             * Object
             * @constant
             */
            object: "chat.completion.chunk";
            /** Service Tier */
            service_tier?: ("auto" | "default" | "flex" | "scale" | "priority") | null;
            /** System Fingerprint */
            system_fingerprint?: string | null;
            usage?: components["schemas"]["CompletionUsage"] | null;
        } & {
            [key: string]: unknown;
        };
        /** ChatCompletionContentPartImageParam */
        ChatCompletionContentPartImageParam: {
            image_url: components["schemas"]["ImageURL"];
            /**
             * Type
             * @constant
             */
            type: "image_url";
        };
        /** ChatCompletionContentPartInputAudioParam */
        ChatCompletionContentPartInputAudioParam: {
            input_audio: components["schemas"]["InputAudio"];
            /**
             * Type
             * @constant
             */
            type: "input_audio";
        };
        /** ChatCompletionContentPartRefusalParam */
        ChatCompletionContentPartRefusalParam: {
            /** Refusal */
            refusal: string;
            /**
             * Type
             * @constant
             */
            type: "refusal";
        };
        /** ChatCompletionContentPartTextParam */
        ChatCompletionContentPartTextParam: {
            /** Text */
            text: string;
            /**
             * Type
             * @constant
             */
            type: "text";
        };
        /** ChatCompletionDeveloperMessageParam */
        ChatCompletionDeveloperMessageParam: {
            /** Content */
            content: string | components["schemas"]["ChatCompletionContentPartTextParam"][];
            /**
             * Role
             * @constant
             */
            role: "developer";
            /** Name */
            name?: string | null;
        };
        /** ChatCompletionFunctionCallOptionParam */
        ChatCompletionFunctionCallOptionParam: {
            /** Name */
            name: string;
        };
        /** ChatCompletionFunctionMessageParam */
        ChatCompletionFunctionMessageParam: {
            /** Content */
            content: string | null;
            /** Name */
            name: string;
            /**
             * Role
             * @constant
             */
            role: "function";
        };
        /** ChatCompletionMessage */
        ChatCompletionMessage: {
            /** Content */
            content?: string | null;
            /** Refusal */
            refusal?: string | null;
            /**
             * Role
             * @constant
             */
            role: "assistant";
            /** Annotations */
            annotations?: components["schemas"]["Annotation"][] | null;
            audio?: components["schemas"]["ChatCompletionAudio"] | null;
            function_call?: components["schemas"]["openai__types__chat__chat_completion_message__FunctionCall"] | null;
            /** Tool Calls */
            tool_calls?: (components["schemas"]["ChatCompletionMessageFunctionToolCall"] | components["schemas"]["ChatCompletionMessageCustomToolCall"])[] | null;
        } & {
            [key: string]: unknown;
        };
        /** ChatCompletionMessageCustomToolCall */
        ChatCompletionMessageCustomToolCall: {
            /** Id */
            id: string;
            custom: components["schemas"]["Custom"];
            /**
             * Type
             * @constant
             */
            type: "custom";
        } & {
            [key: string]: unknown;
        };
        /** ChatCompletionMessageFunctionToolCall */
        ChatCompletionMessageFunctionToolCall: {
            /** Id */
            id: string;
            function: components["schemas"]["Function"];
            /**
             * Type
             * @constant
             */
            type: "function";
        } & {
            [key: string]: unknown;
        };
        /** ChatCompletionMessageToolCallParam */
        ChatCompletionMessageToolCallParam: {
            /** Id */
            id: string;
            function: components["schemas"]["OpenaiTypesChatChatCompletionMessageToolCallParamFunction"];
            /**
             * Type
             * @constant
             */
            type: "function";
        };
        /** ChatCompletionNamedToolChoiceParam */
        ChatCompletionNamedToolChoiceParam: {
            function: components["schemas"]["OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction"];
            /**
             * Type
             * @constant
             */
            type: "function";
        };
        /** ChatCompletionPredictionContentParam */
        ChatCompletionPredictionContentParam: {
            /** Content */
            content: string | components["schemas"]["ChatCompletionContentPartTextParam"][];
            /**
             * Type
             * @constant
             */
            type: "content";
        };
        /** ChatCompletionStreamOptionsParam */
        ChatCompletionStreamOptionsParam: {
            /** Include Usage */
            include_usage?: boolean | null;
        };
        /** ChatCompletionSystemMessageParam */
        ChatCompletionSystemMessageParam: {
            /** Content */
            content: string | components["schemas"]["ChatCompletionContentPartTextParam"][];
            /**
             * Role
             * @constant
             */
            role: "system";
            /** Name */
            name?: string | null;
        };
        /** ChatCompletionTokenLogprob */
        ChatCompletionTokenLogprob: {
            /** Token */
            token: string;
            /** Bytes */
            bytes?: number[] | null;
            /** Logprob */
            logprob: number;
            /** Top Logprobs */
            top_logprobs: components["schemas"]["TopLogprob"][];
        } & {
            [key: string]: unknown;
        };
        /** ChatCompletionToolMessageParam */
        ChatCompletionToolMessageParam: {
            /** Content */
            content: string | components["schemas"]["ChatCompletionContentPartTextParam"][];
            /**
             * Role
             * @constant
             */
            role: "tool";
            /** Tool Call Id */
            tool_call_id: string;
        };
        /** ChatCompletionToolParam */
        ChatCompletionToolParam: {
            function: components["schemas"]["FunctionDefinition"];
            /**
             * Type
             * @constant
             */
            type: "function";
        };
        /** ChatCompletionUserMessageParam */
        ChatCompletionUserMessageParam: {
            /** Content */
            content: string | (components["schemas"]["ChatCompletionContentPartTextParam"] | components["schemas"]["ChatCompletionContentPartImageParam"] | components["schemas"]["ChatCompletionContentPartInputAudioParam"])[];
            /**
             * Role
             * @constant
             */
            role: "user";
            /** Name */
            name?: string | null;
        };
        /** ChoiceDelta */
        ChoiceDelta: {
            /** Content */
            content?: string | null;
            function_call?: components["schemas"]["ChoiceDeltaFunctionCall"] | null;
            /** Refusal */
            refusal?: string | null;
            /** Role */
            role?: ("developer" | "system" | "user" | "assistant" | "tool") | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ChoiceDeltaToolCall"][] | null;
        } & {
            [key: string]: unknown;
        };
        /** ChoiceDeltaFunctionCall */
        ChoiceDeltaFunctionCall: {
            /** Arguments */
            arguments?: string | null;
            /** Name */
            name?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ChoiceDeltaToolCall */
        ChoiceDeltaToolCall: {
            /** Index */
            index: number;
            /** Id */
            id?: string | null;
            function?: components["schemas"]["ChoiceDeltaToolCallFunction"] | null;
            /** Type */
            type?: "function" | null;
        } & {
            [key: string]: unknown;
        };
        /** ChoiceDeltaToolCallFunction */
        ChoiceDeltaToolCallFunction: {
            /** Arguments */
            arguments?: string | null;
            /** Name */
            name?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** CompletionCreateParamsBase */
        CompletionCreateParamsBase: {
            /** Messages */
            messages: (components["schemas"]["ChatCompletionDeveloperMessageParam"] | components["schemas"]["ChatCompletionSystemMessageParam"] | components["schemas"]["ChatCompletionUserMessageParam"] | components["schemas"]["ChatCompletionAssistantMessageParam"] | components["schemas"]["ChatCompletionToolMessageParam"] | components["schemas"]["ChatCompletionFunctionMessageParam"])[];
            /** Model */
            model: string | ("o1" | "o1-2024-12-17" | "o1-preview" | "o1-preview-2024-09-12" | "o1-mini" | "o1-mini-2024-09-12" | "gpt-4o" | "gpt-4o-2024-11-20" | "gpt-4o-2024-08-06" | "gpt-4o-2024-05-13" | "gpt-4o-audio-preview" | "gpt-4o-audio-preview-2024-10-01" | "gpt-4o-audio-preview-2024-12-17" | "gpt-4o-mini-audio-preview" | "gpt-4o-mini-audio-preview-2024-12-17" | "chatgpt-4o-latest" | "gpt-4o-mini" | "gpt-4o-mini-2024-07-18" | "gpt-4-turbo" | "gpt-4-turbo-2024-04-09" | "gpt-4-0125-preview" | "gpt-4-turbo-preview" | "gpt-4-1106-preview" | "gpt-4-vision-preview" | "gpt-4" | "gpt-4-0314" | "gpt-4-0613" | "gpt-4-32k" | "gpt-4-32k-0314" | "gpt-4-32k-0613" | "gpt-3.5-turbo" | "gpt-3.5-turbo-16k" | "gpt-3.5-turbo-0301" | "gpt-3.5-turbo-0613" | "gpt-3.5-turbo-1106" | "gpt-3.5-turbo-0125" | "gpt-3.5-turbo-16k-0613");
            audio?: components["schemas"]["ChatCompletionAudioParam"] | null;
            /** Frequency Penalty */
            frequency_penalty?: number | null;
            /** Function Call */
            function_call?: ("none" | "auto") | components["schemas"]["ChatCompletionFunctionCallOptionParam"] | null;
            /** Functions */
            functions?: components["schemas"]["OpenaiTypesChatCompletionCreateParamsFunction"][] | null;
            /** Logit Bias */
            logit_bias?: {
                [key: string]: number;
            } | null;
            /** Logprobs */
            logprobs?: boolean | null;
            /** Max Completion Tokens */
            max_completion_tokens?: number | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Metadata */
            metadata?: {
                [key: string]: string;
            } | null;
            /** Modalities */
            modalities?: ("text" | "audio")[] | null;
            /** N */
            n?: number | null;
            /** Parallel Tool Calls */
            parallel_tool_calls?: boolean | null;
            prediction?: components["schemas"]["ChatCompletionPredictionContentParam"] | null;
            /** Presence Penalty */
            presence_penalty?: number | null;
            /** Reasoning Effort */
            reasoning_effort?: ("low" | "medium" | "high") | null;
            /** Response Format */
            response_format?: components["schemas"]["ResponseFormatText"] | components["schemas"]["ResponseFormatJSONObject"] | components["schemas"]["ResponseFormatJSONSchema"] | null;
            /** Seed */
            seed?: number | null;
            /** Service Tier */
            service_tier?: ("auto" | "default") | null;
            /** Stop */
            stop?: string | string[] | null;
            /** Store */
            store?: boolean | null;
            stream_options?: components["schemas"]["ChatCompletionStreamOptionsParam"] | null;
            /** Temperature */
            temperature?: number | null;
            /** Tool Choice */
            tool_choice?: ("none" | "auto" | "required") | components["schemas"]["ChatCompletionNamedToolChoiceParam"] | null;
            /** Tools */
            tools?: components["schemas"]["ChatCompletionToolParam"][] | null;
            /** Top Logprobs */
            top_logprobs?: number | null;
            /** Top P */
            top_p?: number | null;
            /** User */
            user?: string | null;
            /**
             * Stream
             * @default false
             */
            stream: boolean;
            /**
             * Transcription Model
             * @default whisper-1
             */
            transcription_model: string;
            /** Transcription Extra Body */
            transcription_extra_body?: {
                [key: string]: unknown;
            } | null;
            /**
             * Speech Model
             * @default tts-1
             */
            speech_model: string;
            /** Speech Extra Body */
            speech_extra_body?: {
                [key: string]: unknown;
            } | null;
        };
        /** CompletionTokensDetails */
        CompletionTokensDetails: {
            /** Accepted Prediction Tokens */
            accepted_prediction_tokens?: number | null;
            /** Audio Tokens */
            audio_tokens?: number | null;
            /** Reasoning Tokens */
            reasoning_tokens?: number | null;
            /** Rejected Prediction Tokens */
            rejected_prediction_tokens?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** CompletionUsage */
        CompletionUsage: {
            /** Completion Tokens */
            completion_tokens: number;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Total Tokens */
            total_tokens: number;
            completion_tokens_details?: components["schemas"]["CompletionTokensDetails"] | null;
            prompt_tokens_details?: components["schemas"]["PromptTokensDetails"] | null;
        } & {
            [key: string]: unknown;
        };
        /** CreateEmbeddingResponse */
        CreateEmbeddingResponse: {
            /**
             * Object
             * @default list
             * @constant
             */
            object: "list";
            /** Data */
            data: components["schemas"]["EmbeddingObject"][];
            /** Model */
            model: string;
            usage: components["schemas"]["EmbeddingUsage"];
        };
        /** CreateSpeechRequestBody */
        CreateSpeechRequestBody: {
            /**
             * Model
             * @description The ID of the model. You can get a list of available models by calling `/v1/models`.
             * @example Systran/faster-distil-whisper-large-v3
             * @example bofenghuang/whisper-large-v2-cv11-french-ct2
             */
            model: string;
            /** Input */
            input: string;
            /** Voice */
            voice: string;
            /** @default mp3 */
            response_format: components["schemas"]["SpeechResponseFormat"];
            /**
             * Speed
             * @default 1
             */
            speed: number;
            /**
             * Stream Format
             * @default audio
             * @enum {string}
             */
            stream_format: "audio" | "sse";
            /** Sample Rate */
            sample_rate?: number | null;
        };
        /** Custom */
        Custom: {
            /** Input */
            input: string;
            /** Name */
            name: string;
        } & {
            [key: string]: unknown;
        };
        /** DiarizationResponse */
        DiarizationResponse: {
            /** Duration */
            duration: number;
            /** Segments */
            segments: components["schemas"]["DiarizationSegment"][];
        };
        /** DiarizationSegment */
        DiarizationSegment: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Speaker */
            speaker: string;
        };
        /** EmbeddingObject */
        EmbeddingObject: {
            /**
             * Object
             * @default embedding
             * @constant
             */
            object: "embedding";
            /**
             * Index
             * @default 0
             * @constant
             */
            index: 0;
            /** Embedding */
            embedding: number[];
        };
        /** EmbeddingUsage */
        EmbeddingUsage: {
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Total Tokens */
            total_tokens: number;
        };
        /** Function */
        Function: {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        } & {
            [key: string]: unknown;
        };
        /** FunctionDefinition */
        FunctionDefinition: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
            /** Strict */
            strict?: boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageURL */
        ImageURL: {
            /** Url */
            url: string;
            /** Detail */
            detail?: ("auto" | "low" | "high") | null;
        };
        /** InputAudio */
        InputAudio: {
            /** Data */
            data: string;
            /**
             * Format
             * @enum {string}
             */
            format: "wav" | "mp3";
        };
        /** JSONSchema */
        JSONSchema: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Schema */
            schema?: {
                [key: string]: unknown;
            } | null;
            /** Strict */
            strict?: boolean | null;
        };
        /** ListAudioModelsResponse */
        ListAudioModelsResponse: {
            /** Models */
            models: components["schemas"]["Model"][];
            /**
             * Object
             * @default list
             */
            object: string;
        };
        /** ListModelsResponse */
        ListModelsResponse: {
            /** Data */
            data: components["schemas"]["Model"][];
            /**
             * Object
             * @default list
             * @constant
             */
            object: "list";
        };
        /** Logprob */
        Logprob: {
            /** Token */
            token?: string | null;
            /** Bytes */
            bytes?: number[] | null;
            /** Logprob */
            logprob?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** MessageResponse */
        MessageResponse: {
            /**
             * Message
             * @description A message describing the result of the operation.
             */
            message: string;
        };
        /**
         * Model
         * @description There may be additional fields in the response that are specific to the model type.
         */
        Model: {
            /** Id */
            id: string;
            /**
             * Created
             * @default 0
             */
            created: number;
            /**
             * Object
             * @default model
             * @constant
             */
            object: "model";
            /** Owned By */
            owned_by: string;
            /** Language */
            language?: string[] | null;
            /**
             * Task
             * @enum {string}
             */
            task: "automatic-speech-recognition" | "text-to-speech" | "speaker-embedding" | "voice-activity-detection";
        } & {
            [key: string]: unknown;
        };
        /** OpenaiTypesChatChatCompletionMessageToolCallParamFunction */
        OpenaiTypesChatChatCompletionMessageToolCallParamFunction: {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        };
        /** OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction */
        OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction: {
            /** Name */
            name: string;
        };
        /** OpenaiTypesChatCompletionCreateParamsFunction */
        OpenaiTypesChatCompletionCreateParamsFunction: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
        };
        /** PromptTokensDetails */
        PromptTokensDetails: {
            /** Audio Tokens */
            audio_tokens?: number | null;
            /** Cached Tokens */
            cached_tokens?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** @enum {string} */
        ResponseFormat: "text" | "json" | "verbose_json" | "srt" | "vtt";
        /** ResponseFormatJSONObject */
        ResponseFormatJSONObject: {
            /**
             * Type
             * @constant
             */
            type: "json_object";
        };
        /** ResponseFormatJSONSchema */
        ResponseFormatJSONSchema: {
            json_schema: components["schemas"]["JSONSchema"];
            /**
             * Type
             * @constant
             */
            type: "json_schema";
        };
        /** ResponseFormatText */
        ResponseFormatText: {
            /**
             * Type
             * @constant
             */
            type: "text";
        };
        /** RunningModelsResponse */
        RunningModelsResponse: {
            /**
             * Models
             * @description List of model IDs that are currently loaded in memory.
             */
            models: string[];
        };
        /** @enum {string} */
        SpeechResponseFormat: "pcm" | "mp3" | "wav" | "flac" | "opus" | "aac";
        /** SpeechTimestamp */
        SpeechTimestamp: {
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** TopLogprob */
        TopLogprob: {
            /** Token */
            token: string;
            /** Bytes */
            bytes?: number[] | null;
            /** Logprob */
            logprob: number;
        } & {
            [key: string]: unknown;
        };
        /** Transcription */
        Transcription: {
            /** Text */
            text: string;
            /** Logprobs */
            logprobs?: components["schemas"]["Logprob"][] | null;
            /** Usage */
            usage?: components["schemas"]["UsageTokens"] | components["schemas"]["UsageDuration"] | null;
        } & {
            [key: string]: unknown;
        };
        /** TranscriptionSegment */
        TranscriptionSegment: {
            /** Id */
            id: number;
            /** Avg Logprob */
            avg_logprob: number;
            /** Compression Ratio */
            compression_ratio: number;
            /** End */
            end: number;
            /** No Speech Prob */
            no_speech_prob: number;
            /** Seek */
            seek: number;
            /** Start */
            start: number;
            /** Temperature */
            temperature: number;
            /** Text */
            text: string;
            /** Tokens */
            tokens: number[];
        } & {
            [key: string]: unknown;
        };
        /** TranscriptionVerbose */
        TranscriptionVerbose: {
            /** Duration */
            duration: number;
            /** Language */
            language: string;
            /** Text */
            text: string;
            /** Segments */
            segments?: components["schemas"]["TranscriptionSegment"][] | null;
            usage?: components["schemas"]["Usage"] | null;
            /** Words */
            words?: components["schemas"]["TranscriptionWord"][] | null;
        } & {
            [key: string]: unknown;
        };
        /** TranscriptionWord */
        TranscriptionWord: {
            /** End */
            end: number;
            /** Start */
            start: number;
            /** Word */
            word: string;
        } & {
            [key: string]: unknown;
        };
        /** Translation */
        Translation: {
            /** Text */
            text: string;
        } & {
            [key: string]: unknown;
        };
        /** TranslationVerbose */
        TranslationVerbose: {
            /** Duration */
            duration: number;
            /** Language */
            language: string;
            /** Text */
            text: string;
            /** Segments */
            segments?: components["schemas"]["TranscriptionSegment"][] | null;
        } & {
            [key: string]: unknown;
        };
        /** Usage */
        Usage: {
            /** Seconds */
            seconds: number;
            /**
             * Type
             * @constant
             */
            type: "duration";
        } & {
            [key: string]: unknown;
        };
        /** UsageDuration */
        UsageDuration: {
            /** Seconds */
            seconds: number;
            /**
             * Type
             * @constant
             */
            type: "duration";
        } & {
            [key: string]: unknown;
        };
        /** UsageTokens */
        UsageTokens: {
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Total Tokens */
            total_tokens: number;
            /**
             * Type
             * @constant
             */
            type: "tokens";
            input_token_details?: components["schemas"]["UsageTokensInputTokenDetails"] | null;
        } & {
            [key: string]: unknown;
        };
        /** UsageTokensInputTokenDetails */
        UsageTokensInputTokenDetails: {
            /** Audio Tokens */
            audio_tokens?: number | null;
            /** Text Tokens */
            text_tokens?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Choice */
        openai__types__chat__chat_completion__Choice: {
            /**
             * Finish Reason
             * @enum {string}
             */
            finish_reason: "stop" | "length" | "tool_calls" | "content_filter" | "function_call";
            /** Index */
            index: number;
            logprobs?: components["schemas"]["openai__types__chat__chat_completion_chunk__ChoiceLogprobs"] | null;
            message: components["schemas"]["ChatCompletionMessage"];
        } & {
            [key: string]: unknown;
        };
        /** Choice */
        openai__types__chat__chat_completion_chunk__Choice: {
            delta: components["schemas"]["ChoiceDelta"];
            /** Finish Reason */
            finish_reason?: ("stop" | "length" | "tool_calls" | "content_filter" | "function_call") | null;
            /** Index */
            index: number;
            logprobs?: components["schemas"]["openai__types__chat__chat_completion_chunk__ChoiceLogprobs"] | null;
        } & {
            [key: string]: unknown;
        };
        /** ChoiceLogprobs */
        openai__types__chat__chat_completion_chunk__ChoiceLogprobs: {
            /** Content */
            content?: components["schemas"]["ChatCompletionTokenLogprob"][] | null;
            /** Refusal */
            refusal?: components["schemas"]["ChatCompletionTokenLogprob"][] | null;
        } & {
            [key: string]: unknown;
        };
        /** FunctionCall */
        openai__types__chat__chat_completion_message__FunctionCall: {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        } & {
            [key: string]: unknown;
        };
        /** FunctionCall */
        speaches__types__chat__FunctionCall: {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    handle_completions_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletionCreateParamsBase"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatCompletion"] | components["schemas"]["ChatCompletionChunk"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    translate_file_v1_audio_translations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_translate_file_v1_audio_translations_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string | components["schemas"]["Translation"] | components["schemas"]["TranslationVerbose"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcribe_file_v1_audio_transcriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_transcribe_file_v1_audio_transcriptions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string | components["schemas"]["Transcription"] | components["schemas"]["TranscriptionVerbose"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_local_models_v1_models_get: {
        parameters: {
            query?: {
                task?: ("automatic-speech-recognition" | "text-to-speech" | "speaker-embedding" | "voice-activity-detection") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListModelsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_local_audio_models_v1_audio_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAudioModelsResponse"];
                };
            };
        };
    };
    list_local_audio_voices_v1_audio_voices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListModelsResponse"];
                };
            };
        };
    };
    get_local_model_v1_models__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_remote_model_v1_models__model_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_model_v1_models__model_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_remote_models_v1_registry_get: {
        parameters: {
            query?: {
                task?: ("automatic-speech-recognition" | "text-to-speech" | "speaker-embedding" | "voice-activity-detection") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListModelsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_running_models_api_ps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunningModelsResponse"];
                };
            };
        };
    };
    load_model_route_api_ps__model_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_running_model_api_ps__model_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    realtime_webrtc_v1_realtime_post: {
        parameters: {
            query: {
                model: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    synthesize_v1_audio_speech_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpeechRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_speech_embedding_v1_audio_speech_embedding_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_create_speech_embedding_v1_audio_speech_embedding_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateEmbeddingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_speech_timestamps_v1_audio_speech_timestamps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_detect_speech_timestamps_v1_audio_speech_timestamps_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeechTimestamp"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diarize_audio_v1_audio_diarization_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_diarize_audio_v1_audio_diarization_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiarizationResponse"];
                    /**
                     * @example SPEAKER uedkc 1 0.000 4.337 <NA> <NA> SPEAKER_03 <NA> <NA>
                     *     SPEAKER uedkc 1 4.337 2.007 <NA> <NA> SPEAKER_00 <NA> <NA>
                     *     SPEAKER uedkc 1 7.568 6.054 <NA> <NA> SPEAKER_03 <NA> <NA>
                     */
                    "text/plain": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
